services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${NGINX_PG_DATABASE:-nginx}
      POSTGRES_USER: ${NGINX_PG_USER:-nginx}
      POSTGRES_PASSWORD: example
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${KONG_PG_DATABASE:-kong}",
          "-U",
          "${KONG_PG_USER:-kong}"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - ./db_data:/var/lib/postgresql/data

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_USER=${NGINX_PG_USER:-nginx}
      - KEYCLOAK_DATABASE_NAME=${NGINX_PG_DATABASE:-nginx}
      - KEYCLOAK_DATABASE_PASSWORD=example
    depends_on:
      - db
    volumes:
      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'

  nginx:
    image: custom-nginx-image:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mynewtheme:/usr/share/nginx/html/mynewtheme